/* const anim = [
    { t: "D_", ms: 90 },
    { t: "De_", ms: 90 },
    { t: "Dev_", ms: 90 },
    { t: "Deve_", ms: 90 },
    { t: "Develo_", ms: 90 },
    { t: "Develop_", ms: 90 },
    { t: "Develope_", ms: 90 },
    { t: "Developer_", ms: 90 },
    { t: "Developer _", ms: 90 },
    { t: "Developer |_", ms: 90 },
    { t: "Developer | _", ms: 90 },
    { t: "Developer | D_", ms: 90 },
    { t: "Developer | Da_", ms: 90 },
    { t: "Developer | Dat_", ms: 90 },
    { t: "Developer | Data_", ms: 90 },
    { t: "Developer | Data _", ms: 90 },
    { t: "Developer | Data S_", ms: 90 },
    { t: "Developer | Data Sc_", ms: 90 },
    { t: "Developer | Data Sci_", ms: 90 },
    { t: "Developer | Data Scie_", ms: 90 },
    { t: "Developer | Data Scien_", ms: 90 },
    { t: "Developer | Data Scient_", ms: 90 },
    { t: "Developer | Data Scienti_", ms: 90 },
    { t: "Developer | Data Scientis_", ms: 90 },
    { t: "Developer | Data Scientist_", ms: 90 },
    { t: "Developer | Data Scientist", ms: 5000 },
    { t: "Developer | Data Scientis_", ms: 90 },
    { t: "Developer | Data Scienti_", ms: 90 },
    { t: "Developer | Data Scient_", ms: 90 },
    { t: "Developer | Data Scien_", ms: 90 },
    { t: "Developer | Data Scie_", ms: 90 },
    { t: "Developer | Data Sci_", ms: 90 },
    { t: "Developer | Data Sc_", ms: 90 },
    { t: "Developer | Data S_", ms: 90 },
    { t: "Developer | Data _", ms: 90 },
    { t: "Developer | Data_", ms: 90 },
    { t: "Developer | Dat_", ms: 90 },
    { t: "Developer | Da_", ms: 90 },
    { t: "Developer | D_", ms: 90 },
    { t: "Developer | _", ms: 90 },
    { t: "Developer |_", ms: 90 },
    { t: "Developer _", ms: 90 },
    { t: "Developer_", ms: 90 },
    { t: "Develope_", ms: 90 },
    { t: "Develop_", ms: 90 },
    { t: "Develo_", ms: 90 },
    { t: "Deve_", ms: 90 },
    { t: "Dev_", ms: 90 },
    { t: "De_", ms: 90 },
    { t: "D_", ms: 90 },
    { t: "_", ms: 90 },
    { t: "D_", ms: 90 },
    { t: "De_", ms: 90 },
    { t: "Dev_", ms: 90 },
    { t: "Deve_", ms: 90 },
    { t: "Develo_", ms: 90 },
    { t: "Develop_", ms: 90 },
    { t: "Develope_", ms: 90 },
    { t: "Developer", ms: 3000 },
    { t: "Develope_", ms: 90 },
    { t: "Develop_", ms: 90 },
    { t: "Develo_", ms: 90 },
    { t: "Deve_", ms: 90 },
    { t: "Dev_", ms: 90 },
    { t: "De_", ms: 90 },
    { t: "D_", ms: 90 },
    { t: "_", ms: 90 },
    { t: "D_", ms: 90 },
    { t: "Da_", ms: 90 },
    { t: "Dat_", ms: 90 },
    { t: "Data_", ms: 90 },
    { t: "Data _", ms: 90 },
    { t: "Data S_", ms: 90 },
    { t: "Data Sc_", ms: 90 },
    { t: "Data Sci_", ms: 90 },
    { t: "Data Scie_", ms: 90 },
    { t: "Data Scien_", ms: 90 },
    { t: "Data Scient_", ms: 90 },
    { t: "Data Scienti_", ms: 90 },
    { t: "Data Scientis_", ms: 90 },
    { t: "Data Scientist", ms: 3000 },
    { t: "Data Scientis_", ms: 90 },
    { t: "Data Scienti_", ms: 90 },
    { t: "Data Scient_", ms: 90 },
    { t: "Data Scien_", ms: 90 },
    { t: "Data Scie_", ms: 90 },
    { t: "Data Sci_", ms: 90 },
    { t: "Data Sc_", ms: 90 },
    { t: "Data S_", ms: 90 },
    { t: "Data _", ms: 90 },
    { t: "Data_", ms: 90 },
    { t: "Dat_", ms: 90 },
    { t: "Da_", ms: 90 },
    { t: "D_", ms: 90 },
    { t: "_", ms: 90 },
];

let index = 0;

function updateText() {
    const step = anim[index];
    document.getElementById('animated-text').textContent = step.t;
    index = (index + 1) % anim.length;
    setTimeout(updateText, step.ms);
}

document.addEventListener('DOMContentLoaded', () => {
    updateText();
}); */